name: Add extension and linting labels to associated opened issues

on:
  issues:
    types: [opened]

jobs:
  label_extension_linting_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Extension Issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # tag=1
        if: contains(toJson(github.event.issue.body), '### Product\n\naxe Extension\n\n')
        with:
          add-labels: 'extension'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Label Linting Issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # tag=1
        if: contains(toJson(github.event.issue.body), '### Product\n\naxe Linter\n\n')
        with:
          add-labels: 'linting'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
